### ISSUE TITLE
If it is a really SEQ2SEQ

### ISSUE THREAD

**Issue by lizhenping** [mnchl-kim/seq2seq-Numpy#1]
you have done a greate job ，but I have read your code ,I think It is  a standerd RNN generate model .i have not see the transform of vector C .if i miss something ?
https://arxiv.org/pdf/1406.1078.pdf

**Comment by mnchl-kim** [comment]
I can't understand what does 'vector C' mean exactly.
If it means 'Encoder-Decoder', this model is not encoder-decoder model.
What I implemented in 'train.py' is just character generate model.

**Comment by lizhenping** [comment]
yeah understood.Just diffenert in name. 3Q.
